export default [
    { id: 1, image: '/images/demo-1.jpg', prompt: 'best quality,a cute anime girl,sunshine,soft features,swing,a blue white edged dress,solo,flower,blue eyes,blush,blue flower,long hair,barefoot,sitting,looking at viewer,blue rose,blue theme,rose,light particles,pale skin,blue background,off shoulder,full body,smile,collarbone,long hair,blue hair,vines,plants,' },
    { id: 2, image: '/images/demo-2.jpg', prompt: 'The city, veiled under storm clouds, cracks open a thread of radiance spills. On the sloping pavement, a girl with rose tinted hair rises on her toes, her red and white sundress a fleeting bloom against the gloom, eyes fixed on the faraway light.' },
    { id: 3, image: '/images/demo-3.jpg', prompt: 'Skyscraper windows a thousand fractured sunsets, a thousand pink haired girls. Her fingertips meet cold glass, but the reflections start blinking out of rhythm. with shafts of folded darkness.' },
    { id: 4, image: '/images/demo-4.jpg', prompt: 'Golden light spills over the meadow, The maid, her hair the color of summer sky, cradles him in her lap his dark strands mingling with the green beneath, a single stalk of grass between his teeth' },
    { id: 5, image: '/images/demo-5.jpg', prompt: 'The illustration decays with the daylight: petals shrivel into ink black veins as the sun dips below the shelves. When he tears the page free, the world outside withers but on paper, a bud swells with stolen spring, with shafts of folded darkness.' },
    { id: 6, image: '/images/demo-6.jpg', prompt: 'Fluorescent lights strip them bare commuters glide through turnstiles, their skeletons clattering like wind chimes. When she crouches down, the moon caught in her ribs flickers in time with her panic.' },
    { id: 7, image: '/images/demo-7.png', prompt: 'Sunlight, grass, A girl lies in the meadow, smiling softly, a blade of grass between her lips.' },
    { id: 8, image: '/images/demo-8.png', prompt: 'Sunlight, dappled shadows, a windchime\'s lazy song,The girl dozes off on the porch swing,her straw hat tilted over her eyes a melting popsicle stick abandoned on the floor,as the summer day hums her to sleep,' },
    { id: 9, image: '/images/demo-9.png', prompt: 'Neon Coke™ in the Cryo Wastes,The last carbonated relic of the old world,its bio luminescent syrup throbbing against permafrost, a corporate logo half scratched off,stll whispering "Drink Me" in binary,' },
    { id: 10, image: '/images/demo-10.png', prompt: 'The rusted leviathan hovers, its belly gnawing on a shipwreck rain sluicing off corroded brass plates, On the rooftop, the old fisherman casts his magnetic line,hauling in flickering spinal circuits to add to his bucket of glowing bolts' },
    { id: 11, image: '/images/demo-11.png', prompt: 'The tree consumes its own rings by sunrise, Today it regurgitates a headstone,the caretaker’s name in crooked chalk letters,plus a child’s shoe,still warm,' },
    { id: 12, image: '/images/demo-12.png', prompt: 'Books slip free from their shelves,drifting like slow motion fireworks,The librarian’s ladder wobbles as she lunges A Brief History of the World escapes again,shedding Sumerian dust and a 1943 bullet casing' },
  ]