export default [
    { id: 1, image: '/images/demo-1.png', prompt: 'A dreamy pastel wonderland, where a sweet feline-eared girl naps atop a giant marshmallow, her silky caramel-colored tail curled around a strawberry shortcake. Twin golden bell charms jingle softly from her ribbon-tied wrists as she stretches, revealing a frilly lace apron over her puffy-sleeved dress. Sunbeams dance through her peach-blossom hair, casting a warm glow on the round cheeks that puff cutely when she yawns. Around her float teacups with tiny wings, pouring endless streams of honey milk into waiting cookies, while plush bunnies and kittens made of cotton clouds nuzzle against her stockinged legs. The air smells of vanilla and apricots, with occasional sparkles forming heart shapes when she giggles in her sleep.' },
    { id: 2, image: '/images/demo-2.png', prompt: 'From atop the moss-grown city gate tower, the view stretches over miles of bustling streets—vermilion-lacquered teahouses and wine shops thronged with patrons, their carved railings entwined with crowds, while silk drapes embroidered with cloud patterns flutter outside fabric emporiums. The cries of street hawkers blend with the rapid plucking of pipa strings, and a troupe of masked nuo dancers weaves through the crowd to the rhythm of drums, startling the brass wind chimes on upturned eaves. Beyond, the setting sun gilds the glazed-tile rooftops, setting the entire neon-clad cityscape ablaze with golden light, as if the very air were drunk with its feverish vitality.' },
    { id: 3, image: '/images/demo-3.png', prompt: 'Rain slashes the night market—a scholar clutches his stall’s collapsing canopy. Then, a white fox shakes itself dry under his eaves, whispering: “Your manuscript bleeds.” He looks down: ink blossoms into peach petals across the drowned pages of Strange Tales.' },
    { id: 4, image: '/images/demo-4.png', prompt: 'Dawn bleeds through mist-cloaked stone lanes, where soybean milk steams in wooden buckets. A pigtailed girl stretches on tiptoe—coins chiming from her palm to the breakfast stall. Then, bells! A monkey in a crimson hat swipes a bun from the bamboo steamer, its owner’s laughter rippling through the crowd.' },
    { id: 5, image: '/images/demo-5.png', prompt: "a weathered concrete wall, set against a gray sky and the skeletal remains of distant industrial pipes. The surface is like a torn newspaper, crammed with graffiti, spray-painted slogans, stickers, and fragments of peeling posters.At the center, in bold red letters, the message \"We Are Still Breathing!\" cuts across the wall like an open wound. Drips of paint still cling to its edges, as if it were written only hours ago. The letters are rough and uneven, full of rage and raw power. In the fading sunlight, the red glimmers faintly — almost like blood.Surrounding the central phrase are layers of smaller texts, some handwritten, others stamped or stenciled:\"Don’t forget who we are\"\"They stole our future\"\"Who’s listening?\"A crude drawing of a lung, labeled \"Last Breath\"At the base of the wall, there's a pile of empty soda cans and burnt-out candles. Cigarette butts and crumpled flyers litter the ground, blown slightly by the wind. A black cat leaps past the edge of the frame, its tail brushing through a patch of weeds sprouting stubbornly from a crack in the concrete."},
    { id: 6, image: '/images/demo-6.png', prompt: 'best quality,a cute anime girl,sunshine,soft features,swing,a blue white edged dress,solo,flower,blue eyes,blush,blue flower,long hair,barefoot,sitting,looking at viewer,blue rose,blue theme,rose,light particles,pale skin,blue background,off shoulder,full body,smile,collarbone,long hair,blue hair,vines,plants,' },
    { id: 7, image: '/images/demo-7.png', prompt: '"The night watchman’s clapper fades,a gas lamp hisses awake at the curb.The hunchback stirs his wrought-iron pot,herbs swirling like forgotten spells."The usual," croaks a salaryman in a loosened tie.When the broth pours, moonlight catchessomething glimmering at the bottom—half a dragon scale."' },
    { id: 8, image: '/images/demo-8.png', prompt: "On a drizzly street, a couple embraces tightly under a transparent umbrella. The girl's hair is gently blown by the wind, while the boy pulls her close. They donu2019t kiss — just gaze into each otheru2019s eyes, as if the whole world has fallen silent." },
    { id: 9, image: '/images/demo-9.png', prompt: 'On a spring afternoon, cherry blossom petals drift gently through the air. A girl in a sailor uniform stands beneath the sakura tree, hearing familiar footsteps behind her. She turns slightly, her eyes soft and shy, cheeks blushing — as if the whole of spring pauses in that moment.' },
    { id: 10, image: '/images/demo-10.png', prompt: 'Anime-style scene.A cute anime girl in a white dress with long, flowing blue hair stands beneath a blooming sakura tree. Her cheeks are faintly blushed, and her eyes glisten with unshed tears. She gently tucks a fallen cherry blossom into the chest pocket of a boy wearing a dark school uniform. He has neatly combed black hair and a gentle, bittersweet expression. The sky behind them glows with sunset hues, and petals drift slowly through the air.' },
    { id: 11, image: '/images/demo-11.png', prompt: 'Anime-style scene.Under a dazzling summer fireworks display, a silver-haired girl in a pale purple yukata nervously clutches her fan. Her head is slightly lowered, heart visibly racing. Beside her stands a boy in a deep blue male yukata, his short black hair neatly styled. He turns to look at her, fireworks reflected in his calm, expectant eyes — waiting for her to say what’s in her heart.' },
    { id: 12, image: '/images/demo-12.png', prompt: 'Anime-style scene, wide aerial view of a fantasy floating city at sunrise, white-stone castle with golden spires in the center, surrounded by floating islands connected by bridges and magical rails, narrow winding streets, red-tiled roofs, soft sunlight piercing through clouds, airships flying in the distance, protective energy shield glowing around the city, cinematic wide shot, reminiscent of Studio Ghibli meets Final Fantasy background art' },
  ]